name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t web .
    - name: Pushing image
      run: |
        aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 544391074589.dkr.ecr.us-east-2.amazonaws.com
        docker tag web:latest 544391074589.dkr.ecr.us-east-2.amazonaws.com/web:latest
        docker push 544391074589.dkr.ecr.us-east-2.amazonaws.com/web:latest
