name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: 3.136.11.188
        username: ec2-user
        key: ${{ secrets.TESTINGEC2 }}
        port: 22
        script: |
          whoami
          pwd
          eval $(ssh-agent)
          ssh-add root/.ssh/my-git-key
          git clone git@github.com:KhandelwalGK/cfntest.git
