name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.0.14
        username: saurav
        key: ${{ secrets.TESTINGEC2 }}
        port: 22
        script: whoami
